# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '6thWeek_Seminar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 6thWeek_Seminar
	pod 'Alamofire', '~> 4.8.2'
	pod 'Kingfisher', '~> 5.0'
	pod 'XLPagerTabStrip', '~> 9.0'
	pod 'BEMCheckBox'
	pod 'iOSDropDown'
  target '6thWeek_SeminarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '6thWeek_SeminarUITests' do
    # Pods for testing
  end

end
